In [1]:
# import the pandas library
import pandas as pd

In [2]:
# input the dataset
# read it somehow
fpath = "../Project 4 Datasets/ncaa-team-data.csv"
# read it into a pandas datastructure
dataset = pd.read_csv(fpath)
dataset

FileNotFoundError: [Errno 2] No such file or directory: '../Project 4 Datasets/ncaa-team-data.csv'

In [22]:
# analyze ncaa-team-data to figure out the top 5 teams in terms of all-time NCAA final wins

# compute the number of wins per team
# go through the dataset, grouped by team
grouped_dataset = []
for team, teamData in dataset.groupby("school"):
    numwins = 0
    # go through teh results of that team
    for result in teamData['ncaa_result']:
        # if it won
        if result == "Won National Final":
            # add to our count
            numwins += 1
    teamResults = {
        'team': team,
        'numWins': numwins
    }
    # add the results to the results dataset
    grouped_dataset.append(teamResults)
# turn the results dataset into a dataframe
print(grouped_dataset)
grouped_dataset = pd.DataFrame(grouped_dataset)
grouped_dataset

# sort the dataset by number of wins, descending
grouped_dataset = grouped_dataset.sort_values(by="numWins", ascending=False)
# show the top 5
top5 = grouped_dataset.head(10)
top5

[{'team': 'air-force', 'numWins': 0}, {'team': 'akron', 'numWins': 0}, {'team': 'alabama', 'numWins': 0}, {'team': 'alabama-birmingham', 'numWins': 0}, {'team': 'alabama-state', 'numWins': 0}, {'team': 'alcorn-state', 'numWins': 0}, {'team': 'allegheny', 'numWins': 0}, {'team': 'american', 'numWins': 0}, {'team': 'appalachian-state', 'numWins': 0}, {'team': 'arizona', 'numWins': 1}, {'team': 'arizona-state', 'numWins': 0}, {'team': 'arkansas', 'numWins': 1}, {'team': 'arkansas-little-rock', 'numWins': 0}, {'team': 'arkansas-state', 'numWins': 0}, {'team': 'army', 'numWins': 0}, {'team': 'auburn', 'numWins': 0}, {'team': 'austin-peay', 'numWins': 0}, {'team': 'ball-state', 'numWins': 0}, {'team': 'baylor', 'numWins': 0}, {'team': 'bethune-cookman', 'numWins': 0}, {'team': 'boise-state', 'numWins': 0}, {'team': 'boston-college', 'numWins': 0}, {'team': 'boston-university', 'numWins': 0}, {'team': 'bowling-green-state', 'numWins': 0}, {'team': 'bradley', 'numWins': 0}, {'team': 'brigham-young', 'numWins': 0}, {'team': 'brooklyn', 'numWins': 0}, {'team': 'brown', 'numWins': 0}, {'team': 'bucknell', 'numWins': 0}, {'team': 'buffalo', 'numWins': 0}, {'team': 'butler', 'numWins': 0}, {'team': 'cal-poly', 'numWins': 0}, {'team': 'cal-state-fullerton', 'numWins': 0}, {'team': 'cal-state-northridge', 'numWins': 0}, {'team': 'california', 'numWins': 1}, {'team': 'california-irvine', 'numWins': 0}, {'team': 'california-santa-barbara', 'numWins': 0}, {'team': 'campbell', 'numWins': 0}, {'team': 'canisius', 'numWins': 0}, {'team': 'carleton-college', 'numWins': 0}, {'team': 'centenary-la', 'numWins': 0}, {'team': 'central-connecticut-state', 'numWins': 0}, {'team': 'central-florida', 'numWins': 0}, {'team': 'central-michigan', 'numWins': 0}, {'team': 'charleston-southern', 'numWins': 0}, {'team': 'charlotte', 'numWins': 0}, {'team': 'chattanooga', 'numWins': 0}, {'team': 'chicago', 'numWins': 0}, {'team': 'chicago-state', 'numWins': 0}, {'team': 'cincinnati', 'numWins': 2}, {'team': 'citadel', 'numWins': 0}, {'team': 'city-college-of-new-york', 'numWins': 1}, {'team': 'clemson', 'numWins': 0}, {'team': 'cleveland-state', 'numWins': 0}, {'team': 'coastal-carolina', 'numWins': 0}, {'team': 'colgate', 'numWins': 0}, {'team': 'college-of-charleston', 'numWins': 0}, {'team': 'colorado', 'numWins': 0}, {'team': 'colorado-college', 'numWins': 0}, {'team': 'colorado-school-of-mines', 'numWins': 0}, {'team': 'colorado-state', 'numWins': 0}, {'team': 'columbia', 'numWins': 0}, {'team': 'connecticut', 'numWins': 4}, {'team': 'coppin-state', 'numWins': 0}, {'team': 'cornell', 'numWins': 0}, {'team': 'creighton', 'numWins': 0}, {'team': 'dartmouth', 'numWins': 0}, {'team': 'davidson', 'numWins': 0}, {'team': 'dayton', 'numWins': 0}, {'team': 'delaware', 'numWins': 0}, {'team': 'delaware-state', 'numWins': 0}, {'team': 'denison', 'numWins': 0}, {'team': 'denver', 'numWins': 0}, {'team': 'depaul', 'numWins': 0}, {'team': 'detroit-mercy', 'numWins': 0}, {'team': 'drake', 'numWins': 0}, {'team': 'drexel', 'numWins': 0}, {'team': 'duke', 'numWins': 5}, {'team': 'duquesne', 'numWins': 0}, {'team': 'east-carolina', 'numWins': 0}, {'team': 'east-tennessee-state', 'numWins': 0}, {'team': 'eastern-illinois', 'numWins': 0}, {'team': 'eastern-kentucky', 'numWins': 0}, {'team': 'eastern-michigan', 'numWins': 0}, {'team': 'eastern-washington', 'numWins': 0}, {'team': 'evansville', 'numWins': 0}, {'team': 'fairfield', 'numWins': 0}, {'team': 'fairleigh-dickinson', 'numWins': 0}, {'team': 'florida', 'numWins': 2}, {'team': 'florida-am', 'numWins': 0}, {'team': 'florida-atlantic', 'numWins': 0}, {'team': 'florida-international', 'numWins': 0}, {'team': 'florida-state', 'numWins': 0}, {'team': 'fordham', 'numWins': 0}, {'team': 'fresno-state', 'numWins': 0}, {'team': 'furman', 'numWins': 0}, {'team': 'george-mason', 'numWins': 0}, {'team': 'george-washington', 'numWins': 0}, {'team': 'georgetown', 'numWins': 1}, {'team': 'georgia', 'numWins': 0}, {'team': 'georgia-southern', 'numWins': 0}, {'team': 'georgia-state', 'numWins': 0}, {'team': 'georgia-tech', 'numWins': 0}, {'team': 'gettysburg', 'numWins': 0}, {'team': 'gonzaga', 'numWins': 0}, {'team': 'grambling', 'numWins': 0}, {'team': 'green-bay', 'numWins': 0}, {'team': 'grinnell', 'numWins': 0}, {'team': 'grove-city', 'numWins': 0}, {'team': 'hampton', 'numWins': 0}, {'team': 'hardin-simmons', 'numWins': 0}, {'team': 'hartford', 'numWins': 0}, {'team': 'harvard', 'numWins': 0}, {'team': 'hawaii', 'numWins': 0}, {'team': 'hofstra', 'numWins': 0}, {'team': 'holy-cross', 'numWins': 1}, {'team': 'houston', 'numWins': 0}, {'team': 'houston-baptist', 'numWins': 0}, {'team': 'howard', 'numWins': 0}, {'team': 'idaho', 'numWins': 0}, {'team': 'idaho-state', 'numWins': 0}, {'team': 'illinois', 'numWins': 0}, {'team': 'illinois-chicago', 'numWins': 0}, {'team': 'illinois-state', 'numWins': 0}, {'team': 'indiana', 'numWins': 5}, {'team': 'indiana-state', 'numWins': 0}, {'team': 'iona', 'numWins': 0}, {'team': 'iowa', 'numWins': 0}, {'team': 'iowa-state', 'numWins': 0}, {'team': 'jackson-state', 'numWins': 0}, {'team': 'jacksonville', 'numWins': 0}, {'team': 'jacksonville-state', 'numWins': 0}, {'team': 'james-madison', 'numWins': 0}, {'team': 'kansas', 'numWins': 3}, {'team': 'kansas-state', 'numWins': 0}, {'team': 'kent-state', 'numWins': 0}, {'team': 'kentucky', 'numWins': 8}, {'team': 'la-salle', 'numWins': 1}, {'team': 'lafayette', 'numWins': 0}, {'team': 'lamar', 'numWins': 0}, {'team': 'lehigh', 'numWins': 0}, {'team': 'liberty', 'numWins': 0}, {'team': 'long-beach-state', 'numWins': 0}, {'team': 'long-island-university', 'numWins': 0}, {'team': 'louisiana-lafayette', 'numWins': 0}, {'team': 'louisiana-monroe', 'numWins': 0}, {'team': 'louisiana-state', 'numWins': 0}, {'team': 'louisiana-tech', 'numWins': 0}, {'team': 'louisville', 'numWins': 3}, {'team': 'loyola-il', 'numWins': 1}, {'team': 'loyola-la', 'numWins': 0}, {'team': 'loyola-marymount', 'numWins': 0}, {'team': 'loyola-md', 'numWins': 0}, {'team': 'maine', 'numWins': 0}, {'team': 'manhattan', 'numWins': 0}, {'team': 'marist', 'numWins': 0}, {'team': 'marquette', 'numWins': 1}, {'team': 'marshall', 'numWins': 0}, {'team': 'maryland', 'numWins': 1}, {'team': 'maryland-baltimore-county', 'numWins': 0}, {'team': 'maryland-eastern-shore', 'numWins': 0}, {'team': 'massachusetts', 'numWins': 0}, {'team': 'mcneese-state', 'numWins': 0}, {'team': 'memphis', 'numWins': 0}, {'team': 'mercer', 'numWins': 0}, {'team': 'miami-fl', 'numWins': 0}, {'team': 'miami-oh', 'numWins': 0}, {'team': 'michigan', 'numWins': 1}, {'team': 'michigan-state', 'numWins': 2}, {'team': 'middle-tennessee', 'numWins': 0}, {'team': 'milwaukee', 'numWins': 0}, {'team': 'minnesota', 'numWins': 0}, {'team': 'mississippi', 'numWins': 0}, {'team': 'mississippi-state', 'numWins': 0}, {'team': 'mississippi-valley-state', 'numWins': 0}, {'team': 'missouri', 'numWins': 0}, {'team': 'missouri-kansas-city', 'numWins': 0}, {'team': 'missouri-state', 'numWins': 0}, {'team': 'monmouth', 'numWins': 0}, {'team': 'montana', 'numWins': 0}, {'team': 'montana-state', 'numWins': 0}, {'team': 'morehead-state', 'numWins': 0}, {'team': 'morgan-state', 'numWins': 0}, {'team': 'mount-st-marys', 'numWins': 0}, {'team': 'mount-union', 'numWins': 0}, {'team': 'muhlenburg', 'numWins': 0}, {'team': 'murray-state', 'numWins': 0}, {'team': 'navy', 'numWins': 0}, {'team': 'nebraska', 'numWins': 0}, {'team': 'nevada', 'numWins': 0}, {'team': 'nevada-las-vegas', 'numWins': 1}, {'team': 'new-hampshire', 'numWins': 0}, {'team': 'new-mexico', 'numWins': 0}, {'team': 'new-mexico-state', 'numWins': 0}, {'team': 'new-orleans', 'numWins': 0}, {'team': 'new-york-university', 'numWins': 0}, {'team': 'niagara', 'numWins': 0}, {'team': 'nicholls-state', 'numWins': 0}, {'team': 'north-carolina', 'numWins': 5}, {'team': 'north-carolina-asheville', 'numWins': 0}, {'team': 'north-carolina-at', 'numWins': 0}, {'team': 'north-carolina-greensboro', 'numWins': 0}, {'team': 'north-carolina-state', 'numWins': 2}, {'team': 'north-carolina-wilmington', 'numWins': 0}, {'team': 'north-dakota', 'numWins': 0}, {'team': 'north-dakota-state', 'numWins': 0}, {'team': 'north-texas', 'numWins': 0}, {'team': 'northeastern', 'numWins': 0}, {'team': 'northern-arizona', 'numWins': 0}, {'team': 'northern-colorado', 'numWins': 0}, {'team': 'northern-illinois', 'numWins': 0}, {'team': 'northern-iowa', 'numWins': 0}, {'team': 'northwestern', 'numWins': 0}, {'team': 'northwestern-state', 'numWins': 0}, {'team': 'notre-dame', 'numWins': 0}, {'team': 'ohio', 'numWins': 0}, {'team': 'ohio-state', 'numWins': 1}, {'team': 'oklahoma', 'numWins': 0}, {'team': 'oklahoma-city', 'numWins': 0}, {'team': 'oklahoma-state', 'numWins': 2}, {'team': 'old-dominion', 'numWins': 0}, {'team': 'oral-roberts', 'numWins': 0}, {'team': 'oregon', 'numWins': 1}, {'team': 'oregon-state', 'numWins': 0}, {'team': 'pacific', 'numWins': 0}, {'team': 'penn-state', 'numWins': 0}, {'team': 'pennsylvania', 'numWins': 0}, {'team': 'pepperdine', 'numWins': 0}, {'team': 'pittsburgh', 'numWins': 0}, {'team': 'portland', 'numWins': 0}, {'team': 'portland-state', 'numWins': 0}, {'team': 'prairie-view', 'numWins': 0}, {'team': 'princeton', 'numWins': 0}, {'team': 'providence', 'numWins': 0}, {'team': 'purdue', 'numWins': 0}, {'team': 'radford', 'numWins': 0}, {'team': 'rhode-island', 'numWins': 0}, {'team': 'rice', 'numWins': 0}, {'team': 'richmond', 'numWins': 0}, {'team': 'rider', 'numWins': 0}, {'team': 'robert-morris', 'numWins': 0}, {'team': 'rutgers', 'numWins': 0}, {'team': 'sacramento-state', 'numWins': 0}, {'team': 'saint-francis-pa', 'numWins': 0}, {'team': 'saint-josephs', 'numWins': 0}, {'team': 'saint-louis', 'numWins': 0}, {'team': 'saint-marys-ca', 'numWins': 0}, {'team': 'saint-peters', 'numWins': 0}, {'team': 'sam-houston-state', 'numWins': 0}, {'team': 'samford', 'numWins': 0}, {'team': 'san-diego', 'numWins': 0}, {'team': 'san-diego-state', 'numWins': 0}, {'team': 'san-francisco', 'numWins': 2}, {'team': 'san-jose-state', 'numWins': 0}, {'team': 'santa-clara', 'numWins': 0}, {'team': 'seattle', 'numWins': 0}, {'team': 'seton-hall', 'numWins': 0}, {'team': 'siena', 'numWins': 0}, {'team': 'south-alabama', 'numWins': 0}, {'team': 'south-carolina', 'numWins': 0}, {'team': 'south-carolina-state', 'numWins': 0}, {'team': 'south-florida', 'numWins': 0}, {'team': 'southeast-missouri-state', 'numWins': 0}, {'team': 'southeastern-louisiana', 'numWins': 0}, {'team': 'southern', 'numWins': 0}, {'team': 'southern-california', 'numWins': 0}, {'team': 'southern-illinois', 'numWins': 0}, {'team': 'southern-methodist', 'numWins': 0}, {'team': 'southern-mississippi', 'numWins': 0}, {'team': 'southern-utah', 'numWins': 0}, {'team': 'southwestern-ks', 'numWins': 0}, {'team': 'springfield', 'numWins': 0}, {'team': 'st-bonaventure', 'numWins': 0}, {'team': 'st-francis-ny', 'numWins': 0}, {'team': 'st-johns-ny', 'numWins': 0}, {'team': 'stanford', 'numWins': 1}, {'team': 'stephen-f-austin', 'numWins': 0}, {'team': 'stetson', 'numWins': 0}, {'team': 'syracuse', 'numWins': 1}, {'team': 'temple', 'numWins': 0}, {'team': 'tennessee', 'numWins': 0}, {'team': 'tennessee-martin', 'numWins': 0}, {'team': 'tennessee-state', 'numWins': 0}, {'team': 'tennessee-tech', 'numWins': 0}, {'team': 'texas', 'numWins': 0}, {'team': 'texas-am', 'numWins': 0}, {'team': 'texas-arlington', 'numWins': 0}, {'team': 'texas-christian', 'numWins': 0}, {'team': 'texas-el-paso', 'numWins': 1}, {'team': 'texas-pan-american', 'numWins': 0}, {'team': 'texas-san-antonio', 'numWins': 0}, {'team': 'texas-southern', 'numWins': 0}, {'team': 'texas-state', 'numWins': 0}, {'team': 'texas-tech', 'numWins': 0}, {'team': 'toledo', 'numWins': 0}, {'team': 'towson', 'numWins': 0}, {'team': 'troy', 'numWins': 0}, {'team': 'tulane', 'numWins': 0}, {'team': 'tulsa', 'numWins': 0}, {'team': 'ucla', 'numWins': 11}, {'team': 'utah', 'numWins': 1}, {'team': 'utah-state', 'numWins': 0}, {'team': 'valparaiso', 'numWins': 0}, {'team': 'vanderbilt', 'numWins': 0}, {'team': 'vermont', 'numWins': 0}, {'team': 'villanova', 'numWins': 2}, {'team': 'virginia', 'numWins': 0}, {'team': 'virginia-commonwealth', 'numWins': 0}, {'team': 'virginia-military-institute', 'numWins': 0}, {'team': 'virginia-tech', 'numWins': 0}, {'team': 'wabash', 'numWins': 0}, {'team': 'wagner', 'numWins': 0}, {'team': 'wake-forest', 'numWins': 0}, {'team': 'washburn', 'numWins': 0}, {'team': 'washington', 'numWins': 0}, {'team': 'washington-lee', 'numWins': 0}, {'team': 'washington-mo', 'numWins': 0}, {'team': 'washington-state', 'numWins': 0}, {'team': 'weber-state', 'numWins': 0}, {'team': 'west-texas-am', 'numWins': 0}, {'team': 'west-virginia', 'numWins': 0}, {'team': 'western-carolina', 'numWins': 0}, {'team': 'western-illinois', 'numWins': 0}, {'team': 'western-kentucky', 'numWins': 0}, {'team': 'western-michigan', 'numWins': 0}, {'team': 'westminster-pa', 'numWins': 0}, {'team': 'wichita-state', 'numWins': 0}, {'team': 'william-mary', 'numWins': 0}, {'team': 'winthrop', 'numWins': 0}, {'team': 'wisconsin', 'numWins': 1}, {'team': 'wisconsin-stevens-point', 'numWins': 0}, {'team': 'wofford', 'numWins': 0}, {'team': 'wooster', 'numWins': 0}, {'team': 'wright-state', 'numWins': 0}, {'team': 'wyoming', 'numWins': 1}, {'team': 'xavier', 'numWins': 0}, {'team': 'yale', 'numWins': 0}, {'team': 'youngstown-state', 'numWins': 0}]

               team  numWins
299            ucla       11
136        kentucky        8
124         indiana        5
77             duke        5
198  north-carolina        5
62      connecticut        4
133          kansas        3
148      louisville        3
49       cincinnati        2
88          florida        2

In [12]:
# show me all the times that ucla won
dataset[(dataset['ncaa_result']=="Won National Final") & (dataset['school'] == "ucla")].sort_values(by="year", ascending=False)

,school,conf,rk,w,l,wl,srs,sos,pts_for,pts_vs,pts_total,ap_pre,ap_high,ap_final,pts_diff,ncaa_result,ncaa_numeric,season,coaches,year
20960,ucla,Pac-10,23,31.0,2.0,0.939,23.74,10.08,87.5,NaN,NaN,6.0,1.0,1.0,NaN,Won National Final,48.0,1994-95,Jim Harrick (31-2),1994.0
20980,ucla,Pac-8,43,28.0,3.0,0.903,21.07,8.55,NaN,NaN,NaN,2.0,1.0,1.0,NaN,Won National Final,48.0,1974-75,John Wooden (28-3),1974.0
20982,ucla,Pac-8,45,30.0,0.0,1.000,27.98,6.71,NaN,NaN,NaN,1.0,1.0,1.0,NaN,Won National Final,48.0,1972-73,John Wooden (30-0),1972.0
20983,ucla,Pac-8,46,30.0,0.0,1.000,33.79,3.46,NaN,NaN,NaN,1.0,1.0,1.0,NaN,Won National Final,48.0,1971-72,John Wooden (30-0),1971.0
20984,ucla,Pac-8,47,29.0,1.0,0.967,20.91,5.98,NaN,NaN,NaN,1.0,1.0,1.0,NaN,Won National Final,48.0,1970-71,John Wooden (29-1),1970.0
20985,ucla,Pac-8,48,28.0,2.0,0.933,25.02,6.42,NaN,NaN,NaN,4.0,1.0,2.0,NaN,Won National Final,48.0,1969-70,John Wooden (28-2),1969.0
20986,ucla,Pac-8,49,29.0,1.0,0.967,26.69,5.85,NaN,NaN,NaN,1.0,1.0,1.0,NaN,Won National Final,48.0,1968-69,John Wooden (29-1),1968.0
20987,ucla,AAWU,50,29.0,1.0,0.967,32.56,6.33,NaN,NaN,NaN,1.0,1.0,2.0,NaN,Won National Final,48.0,1967-68,John Wooden (29-1),1967.0
20988,ucla,AAWU,51,30.0,0.0,1.000,29.39,3.49,NaN,NaN,NaN,1.0,1.0,1.0,NaN,Won National Final,48.0,1966-67,John Wooden (30-0),1966.0
20990,ucla,AAWU,53,28.0,2.0,0.933,21.33,7.09,NaN,NaN,NaN,2.0,1.0,2.0,NaN,Won National Final,48.0,1964-65,John Wooden (28-2),1964.0
20991,ucla,AAWU,54,30.0,0.0,1.000,22.51,4.35,NaN,NaN,NaN,30.0,1.0,1.0,NaN,Won National Final,48.0,1963-64,John Wooden (30-0),1963.0

In [18]:
grouped_dataset2 = []
for group, groupData in dataset.groupby("conf"):
    numwins = 0
    # go through teh results of that team
    for result in groupData['ncaa_result']:
        # if it won
        if result == "Won National Final":
            # add to our count
            numwins += 1
    groupResults = {
        'conf': group,
        'numWins': numwins
    }
    # add the results to the results dataset
    grouped_dataset2.append(groupResults)
# turn the results dataset into a dataframe
grouped_dataset2 = pd.DataFrame(grouped_dataset2)
grouped_dataset2.sort_values(by="numWins", ascending=False)

        conf  numWins
4        ACC       13
60       SEC       11
16   Big Ten       10
13  Big East        8
58     Pac-8        6
..       ...      ...
35       MAC        0
1      A-Sun        0
37       MCC        0
38      MEAC        0
72    Yankee        0

[73 rows x 2 columns]